'use client';

/**
 * /discover — sonic similarity exploration.
 *
 * Track selection retains metadata and item links. Remote analysis and new
 * vector/index writes are disabled until recording permissions are verified.
 * Existing catalog records and the similarity read endpoint remain intact.
 */

import { useCallback } from 'react';

import type { SearchHit } from '@/lib/sources/types';
import { useSongAnalysis, type SongMeta } from '@/app/hooks/useSongAnalysis';

import AnalysisSkeleton from '@/app/components/AnalysisSkeleton';
import AudioAnalysisResultsView from '@/app/components/AudioAnalysisResults';
import SimilarSongs from '@/app/components/SimilarSongs';
import SongSearch from '@/app/components/SongSearch';
import WaveformPlayer from '@/app/components/WaveformPlayer';
import TrackExploration from '@/app/components/TrackExploration';
import { Card } from '@/app/components/ui/Card';
import { Spectrum } from '@/app/components/ui/Spectrum';
import { toast } from '@/app/components/ui/Toast';

export default function DiscoverPage() {
  const audio = useSongAnalysis();

  const handlePick = useCallback(
    (song: SongMeta) => void audio.analyzeSong(song),
    [audio],
  );

  const handleSearchPick = useCallback(
    (hit: SearchHit) => void audio.analyzeSong(hit.song),
    [audio],
  );

  const handleExport = useCallback(() => {
    const analysis = audio.analysis;
    if (!analysis) return;
    void navigator.clipboard
      .writeText(
        `${audio.song?.title ?? 'Song'} — ${analysis.mood}, ${analysis.vibe}, ${analysis.bpm} BPM\n\n${analysis.detailedAnalysis}\n\n— Generated by SongAnalyzer`,
      )
      .then(() => toast.success('Copied to clipboard'));
  }, [audio.analysis, audio.song]);

  return (
    <main className="relative min-h-screen overflow-hidden bg-[var(--bg-base)] text-[var(--text-hi)]">
      <div
        aria-hidden
        className="pointer-events-none absolute inset-0 -z-10"
        style={{
          background:
            'radial-gradient(ellipse 70% 45% at 50% -5%, color-mix(in_oklab, var(--accent-glow) 45%, transparent), transparent 65%)',
        }}
      />

      <div className="container mx-auto max-w-4xl px-4 pb-16 pt-12">
        <header className="mb-8 space-y-2 text-center">
          <h1 className="font-display text-4xl tracking-tight md:text-5xl">
            <span className="text-[var(--text-hi)]">Find what</span>{' '}
            <span className="text-accent-gradient italic">feels the same.</span>
          </h1>
          <p className="mx-auto max-w-xl text-sm text-[var(--text-med)] md:text-base">
            Explore track details and listening links. Remote audio analysis and new
            catalog indexing are paused while recording permissions are reviewed.
          </p>
        </header>

        <div className="mb-6">
          <SongSearch onSelect={handleSearchPick} placeholder="Start from a song…" />
        </div>

        {audio.song && (
          <div className="mb-6">
            <TrackExploration
              song={audio.song} stage={audio.stage} loading={audio.loading}
              error={audio.error} hasAnalysis={Boolean(audio.analysis)}
              onClear={() => {
                audio.reset();
                document.querySelector<HTMLInputElement>('[role="combobox"]')?.focus();
              }}
            />
          </div>
        )}

        {audio.loading ? (
          <AnalysisSkeleton />
        ) : audio.analysis ? (
          <div className="space-y-4">
            {audio.audioSrc && (
              <WaveformPlayer
                src={audio.audioSrc}
                beatGrid={audio.analysis.v2?.beatGrid}
                duration={audio.analysis.duration}
              />
            )}
            <SimilarSongs songId={audio.songId} onPick={handlePick} />
            <AudioAnalysisResultsView
              analysis={audio.analysis}
              onExport={handleExport}
              analysisId={audio.analysisId ?? undefined}
            />
          </div>
        ) : !audio.song ? (
          <Card variant="elev1" className="py-14 text-center">
            <div className="mx-auto mb-5 h-10 w-40 opacity-60">
              <Spectrum bars={20} className="h-full w-full" />
            </div>
            <h3 className="mb-2 font-display text-xl text-[var(--text-hi)]">
              Start with a track you love
            </h3>
            <p className="mx-auto max-w-md text-sm text-[var(--text-med)]">
              Search above for track details and listening links. You can measure a
              local recording in Analyze; those insights stay on your device.
            </p>
          </Card>
        ) : null}
      </div>
    </main>
  );
}
