'use client';

/**
 * /identify — Shazam-style song identification from instrumental audio.
 *
 * The IdentifyListener records ~10s, fingerprints it in a Web Worker, and
 * matches against our constellation catalog (AudD world-catalog fallback
 * when configured). A match hands straight into the shared analysis
 * pipeline, so the identified song's mood tints the page seconds later.
 */

import { useCallback } from 'react';

import type { Song } from '@/lib/sources/types';
import { useSongAnalysis } from '@/app/hooks/useSongAnalysis';

import IdentifyListener from '@/app/components/IdentifyListener';
import AnalysisSkeleton from '@/app/components/AnalysisSkeleton';
import AudioAnalysisResultsView from '@/app/components/AudioAnalysisResults';
import SimilarSongs from '@/app/components/SimilarSongs';
import WaveformPlayer from '@/app/components/WaveformPlayer';
import { toast } from '@/app/components/ui/Toast';

export default function IdentifyPage() {
  const audio = useSongAnalysis();

  const handleMatched = useCallback(
    (song: Song) => {
      if (song.previewUrl) {
        void audio.analyzeSong(song);
      } else {
        toast.message(song.title, {
          description: 'Identified — no preview available for auto-analysis.',
        });
      }
    },
    [audio],
  );

  const handleAudioExport = useCallback(() => {
    const analysis = audio.analysis;
    if (!analysis) return;
    const text = [
      `Audio Analysis — ${audio.song?.title ?? 'identified song'}`,
      `Mood: ${analysis.mood} · Vibe: ${analysis.vibe} · Energy: ${analysis.energy}`,
      `Tempo: ${analysis.bpm} BPM`,
      '',
      analysis.detailedAnalysis,
      '',
      '— Generated by SongAnalyzer',
    ].join('\n');
    void navigator.clipboard.writeText(text).then(() => toast.success('Copied to clipboard'));
  }, [audio.analysis, audio.song]);

  return (
    <main className="relative min-h-screen overflow-hidden bg-[var(--bg-base)] text-[var(--text-hi)]">
      <div
        aria-hidden
        className="pointer-events-none absolute inset-0 -z-10"
        style={{
          background:
            'radial-gradient(ellipse 70% 45% at 50% -5%, color-mix(in_oklab, var(--accent-glow) 55%, transparent), transparent 65%)',
        }}
      />

      <div className="container mx-auto max-w-3xl px-4 pb-16 pt-12">
        <header className="mb-8 space-y-2 text-center">
          <h1 className="font-display text-4xl tracking-tight md:text-5xl">
            <span className="text-[var(--text-hi)]">Name that</span>{' '}
            <span className="text-accent-gradient italic">beat.</span>
          </h1>
          <p className="mx-auto max-w-xl text-sm text-[var(--text-med)] md:text-base">
            Hold your device to the music. The instrumental&rsquo;s spectral constellation is
            fingerprinted in your browser — no audio leaves your device for catalog matches.
          </p>
        </header>

        <IdentifyListener onMatched={handleMatched} />

        {(audio.loading || audio.analysis) && (
          <div className="mt-8 space-y-4">
            {audio.loading ? (
              <AnalysisSkeleton />
            ) : (
              audio.analysis && (
                <>
                  {audio.audioSrc && (
                    <WaveformPlayer
                      src={audio.audioSrc}
                      beatGrid={audio.analysis.v2?.beatGrid}
                      duration={audio.analysis.duration}
                    />
                  )}
                  <AudioAnalysisResultsView
                    analysis={audio.analysis}
                    onExport={handleAudioExport}
                    analysisId={audio.analysisId ?? undefined}
                  />
                  <SimilarSongs
                    songId={audio.songId}
                    onPick={(song) => void audio.analyzeSong(song)}
                  />
                </>
              )
            )}
          </div>
        )}
      </div>
    </main>
  );
}
