'use client';

import { useState, useCallback } from 'react';
import { AnalysisResult, AudioAnalysisResult, HistoryEntry } from '@/lib/types';
import { saveToHistory } from '@/lib/history';
import { analyzeAudioFile } from '@/lib/audio-analysis';
import ThemeToggle from './components/ThemeToggle';
import LyricsInput from './components/LyricsInput';
import AnalysisResults from './components/AnalysisResults';
import AnalysisSkeleton from './components/AnalysisSkeleton';
import EmptyState from './components/EmptyState';
import SampleLyricPicker from './components/SampleLyricPicker';
import HistoryPanel from './components/HistoryPanel';
import ModeTabs, { AnalysisMode } from './components/ModeTabs';
import AudioUpload from './components/AudioUpload';
import AudioAnalysisResultsView from './components/AudioAnalysisResults';

export default function Home() {
  // ── Shared state ──
  const [mode, setMode] = useState<AnalysisMode>('lyrics');
  const [copied, setCopied] = useState(false);

  // ── Lyrics state ──
  const [lyrics, setLyrics] = useState('');
  const [lyricsAnalysis, setLyricsAnalysis] = useState<AnalysisResult | null>(null);
  const [lyricsLoading, setLyricsLoading] = useState(false);
  const [lyricsError, setLyricsError] = useState('');
  const [historyKey, setHistoryKey] = useState(0);

  // ── Audio state ──
  const [audioAnalysis, setAudioAnalysis] = useState<AudioAnalysisResult | null>(null);
  const [audioLoading, setAudioLoading] = useState(false);
  const [audioError, setAudioError] = useState('');
  const [audioFileName, setAudioFileName] = useState<string | null>(null);

  // ── Lyrics handlers ──
  const analyzeLyrics = useCallback(async () => {
    if (!lyrics.trim()) {
      setLyricsError('Please enter some lyrics to analyze');
      return;
    }

    setLyricsLoading(true);
    setLyricsError('');
    setLyricsAnalysis(null);

    try {
      const response = await fetch('/api/analyze', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ lyrics }),
      });

      if (!response.ok) {
        const errorData = await response.json().catch(() => null);
        throw new Error(errorData?.error ?? 'Failed to analyze lyrics');
      }

      const result: AnalysisResult = await response.json();
      setLyricsAnalysis(result);

      saveToHistory(lyrics, result);
      setHistoryKey((k) => k + 1);
    } catch (err) {
      setLyricsError(err instanceof Error ? err.message : 'An error occurred');
    } finally {
      setLyricsLoading(false);
    }
  }, [lyrics]);

  const handleLyricsChange = useCallback(
    (value: string) => {
      setLyrics(value);
      if (lyricsAnalysis) {
        setLyricsAnalysis(null);
        setLyricsError('');
      }
    },
    [lyricsAnalysis],
  );

  const handleRestoreHistory = useCallback((entry: HistoryEntry) => {
    setLyricsAnalysis(entry.result);
    setLyricsError('');
  }, []);

  const handleLyricsExport = useCallback(() => {
    if (!lyricsAnalysis) return;
    const text = [
      `Song Lyric Analysis`,
      `───────────────────`,
      `Mood:      ${lyricsAnalysis.mood}`,
      `Vibe:      ${lyricsAnalysis.vibe}`,
      `Energy:    ${lyricsAnalysis.energy}`,
      `Sentiment: ${lyricsAnalysis.sentiment}`,
      `Themes:    ${lyricsAnalysis.themes.join(', ')}`,
      `Confidence: ${Math.round(lyricsAnalysis.confidence * 100)}%`,
      ``,
      lyricsAnalysis.detailedAnalysis,
      ``,
      `— Generated by Song Lyric Analyzer`,
    ].join('\n');
    navigator.clipboard.writeText(text).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  }, [lyricsAnalysis]);

  // ── Audio handlers ──
  const handleAudioFile = useCallback(async (file: File) => {
    setAudioFileName(file.name);
    setAudioLoading(true);
    setAudioError('');
    setAudioAnalysis(null);

    try {
      const result = await analyzeAudioFile(file);
      setAudioAnalysis(result);
    } catch (err) {
      setAudioError(
        err instanceof Error
          ? err.message
          : 'Could not analyze the audio file. Make sure it contains valid audio.',
      );
    } finally {
      setAudioLoading(false);
    }
  }, []);

  const handleAudioExport = useCallback(() => {
    if (!audioAnalysis) return;
    const text = [
      `Audio Analysis`,
      `──────────────`,
      `Mood:      ${audioAnalysis.mood}`,
      `Vibe:      ${audioAnalysis.vibe}`,
      `Energy:    ${audioAnalysis.energy}`,
      `Sentiment: ${audioAnalysis.sentiment}`,
      `Tempo:     ${audioAnalysis.bpm} BPM (${audioAnalysis.tempo})`,
      `Duration:  ${Math.round(audioAnalysis.duration)}s`,
      `Chars:     ${audioAnalysis.characteristics.join(', ')}`,
      `Confidence: ${Math.round(audioAnalysis.confidence * 100)}%`,
      ``,
      audioAnalysis.detailedAnalysis,
      ``,
      `— Generated by Song Lyric Analyzer`,
    ].join('\n');
    navigator.clipboard.writeText(text).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  }, [audioAnalysis]);

  // ── Render ──
  return (
    <main className="min-h-screen bg-gradient-to-br from-slate-50 to-slate-100 dark:from-slate-900 dark:to-slate-800 transition-colors">
      {/* Theme Toggle */}
      <div className="absolute top-4 right-4 z-10">
        <ThemeToggle />
      </div>

      {/* Copied toast */}
      {copied && (
        <div className="fixed top-4 left-1/2 -translate-x-1/2 z-50 bg-gray-900 dark:bg-gray-100 text-white dark:text-gray-900 px-4 py-2 rounded-lg shadow-lg text-sm font-medium animate-fade-in">
          Copied to clipboard!
        </div>
      )}

      <div className="container mx-auto px-4 py-12 max-w-5xl">
        {/* Header */}
        <header className="text-center mb-6">
          <h1 className="text-5xl font-bold mb-4 pb-2 bg-gradient-to-r from-blue-600 to-purple-600 bg-clip-text text-transparent leading-tight">
            Song Analyzer
          </h1>
          <p className="text-lg text-gray-600 dark:text-gray-300">
            Discover the mood, vibe, and emotional essence of any song
          </p>
        </header>

        {/* Mode tabs */}
        <ModeTabs mode={mode} onChange={setMode} />

        {/* ════════════ LYRICS MODE ════════════ */}
        {mode === 'lyrics' && (
          <>
            <SampleLyricPicker onSelect={(s) => handleLyricsChange(s)} />

            <div className="grid gap-8 md:grid-cols-1 lg:grid-cols-2">
              <div>
                <LyricsInput
                  lyrics={lyrics}
                  onLyricsChange={handleLyricsChange}
                  onAnalyze={analyzeLyrics}
                  loading={lyricsLoading}
                  error={lyricsError}
                />
                <HistoryPanel onRestore={handleRestoreHistory} refreshKey={historyKey} />
              </div>

              <div>
                {lyricsLoading ? (
                  <AnalysisSkeleton />
                ) : lyricsAnalysis ? (
                  <AnalysisResults analysis={lyricsAnalysis} onExport={handleLyricsExport} />
                ) : (
                  <EmptyState />
                )}
              </div>
            </div>
          </>
        )}

        {/* ════════════ AUDIO MODE ════════════ */}
        {mode === 'audio' && (
          <div className="grid gap-8 md:grid-cols-1 lg:grid-cols-2">
            <div>
              <AudioUpload
                onFileSelected={handleAudioFile}
                loading={audioLoading}
                error={audioError}
                fileName={audioFileName}
              />
            </div>

            <div>
              {audioLoading ? (
                <AnalysisSkeleton />
              ) : audioAnalysis ? (
                <AudioAnalysisResultsView analysis={audioAnalysis} onExport={handleAudioExport} />
              ) : (
                <div className="bg-white dark:bg-slate-800 rounded-2xl shadow-xl p-12 border border-gray-200 dark:border-slate-700 text-center">
                  <div className="text-6xl mb-4">🎧</div>
                  <h3 className="text-xl font-semibold text-gray-700 dark:text-gray-300 mb-2">
                    Ready to Analyze Audio
                  </h3>
                  <p className="text-gray-500 dark:text-gray-400">
                    Upload an audio file to detect mood from the music itself — beat, rhythm, energy, and tone
                  </p>
                </div>
              )}
            </div>
          </div>
        )}

        {/* Footer */}
        <footer className="mt-16 text-center text-sm text-gray-500 dark:text-gray-400 space-y-1">
          <p>Analyze lyrics or audio — supports multiple languages with automatic translation</p>
          <p>💡 Tip: Paste full song lyrics or upload a longer audio clip for more accurate results</p>
        </footer>
      </div>
    </main>
  );
}
