'use client';

import { useState, useCallback } from 'react';
import { AnalysisResult, HistoryEntry } from '@/lib/types';
import { saveToHistory } from '@/lib/history';
import ThemeToggle from './components/ThemeToggle';
import LyricsInput from './components/LyricsInput';
import AnalysisResults from './components/AnalysisResults';
import AnalysisSkeleton from './components/AnalysisSkeleton';
import EmptyState from './components/EmptyState';
import SampleLyricPicker from './components/SampleLyricPicker';
import HistoryPanel from './components/HistoryPanel';

export default function Home() {
  const [lyrics, setLyrics] = useState('');
  const [analysis, setAnalysis] = useState<AnalysisResult | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [historyKey, setHistoryKey] = useState(0);
  const [copied, setCopied] = useState(false);

  const analyzeLyrics = useCallback(async () => {
    if (!lyrics.trim()) {
      setError('Please enter some lyrics to analyze');
      return;
    }

    setLoading(true);
    setError('');
    setAnalysis(null);

    try {
      const response = await fetch('/api/analyze', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ lyrics }),
      });

      if (!response.ok) {
        const errorData = await response.json().catch(() => null);
        throw new Error(errorData?.error ?? 'Failed to analyze lyrics');
      }

      const result: AnalysisResult = await response.json();
      setAnalysis(result);

      // Persist to history
      saveToHistory(lyrics, result);
      setHistoryKey((k) => k + 1);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'An error occurred');
    } finally {
      setLoading(false);
    }
  }, [lyrics]);

  const handleExport = useCallback(() => {
    if (!analysis) return;
    const text = [
      `Song Lyric Analysis`,
      `───────────────────`,
      `Mood:      ${analysis.mood}`,
      `Vibe:      ${analysis.vibe}`,
      `Energy:    ${analysis.energy}`,
      `Sentiment: ${analysis.sentiment}`,
      `Themes:    ${analysis.themes.join(', ')}`,
      `Confidence: ${Math.round(analysis.confidence * 100)}%`,
      ``,
      analysis.detailedAnalysis,
      ``,
      `— Generated by Song Lyric Analyzer`,
    ].join('\n');

    navigator.clipboard.writeText(text).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  }, [analysis]);

  const handleRestoreHistory = useCallback((entry: HistoryEntry) => {
    setAnalysis(entry.result);
    setError('');
  }, []);

  const handleLyricsChange = useCallback((value: string) => {
    setLyrics(value);
    if (analysis) {
      setAnalysis(null);
      setError('');
    }
  }, [analysis]);

  return (
    <main className="min-h-screen bg-gradient-to-br from-slate-50 to-slate-100 dark:from-slate-900 dark:to-slate-800 transition-colors">
      {/* Theme Toggle */}
      <div className="absolute top-4 right-4 z-10">
        <ThemeToggle />
      </div>

      {/* Copied toast */}
      {copied && (
        <div className="fixed top-4 left-1/2 -translate-x-1/2 z-50 bg-gray-900 dark:bg-gray-100 text-white dark:text-gray-900 px-4 py-2 rounded-lg shadow-lg text-sm font-medium animate-fade-in">
          Copied to clipboard!
        </div>
      )}

      <div className="container mx-auto px-4 py-12 max-w-5xl">
        {/* Header */}
        <header className="text-center mb-10">
          <h1 className="text-5xl font-bold mb-4 pb-2 bg-gradient-to-r from-blue-600 to-purple-600 bg-clip-text text-transparent leading-tight">
            Song Lyric Analyzer
          </h1>
          <p className="text-lg text-gray-600 dark:text-gray-300">
            Discover the mood, vibe, and emotional essence of any song
          </p>
        </header>

        {/* Sample lyrics quick-start */}
        <SampleLyricPicker onSelect={(s) => handleLyricsChange(s)} />

        {/* Main Content Grid */}
        <div className="grid gap-8 md:grid-cols-1 lg:grid-cols-2">
          {/* Left column — input */}
          <div>
            <LyricsInput
              lyrics={lyrics}
              onLyricsChange={handleLyricsChange}
              onAnalyze={analyzeLyrics}
              loading={loading}
              error={error}
            />

            {/* History panel */}
            <HistoryPanel onRestore={handleRestoreHistory} refreshKey={historyKey} />
          </div>

          {/* Right column — results */}
          <div>
            {loading ? (
              <AnalysisSkeleton />
            ) : analysis ? (
              <AnalysisResults analysis={analysis} onExport={handleExport} />
            ) : (
              <EmptyState />
            )}
          </div>
        </div>

        {/* Footer */}
        <footer className="mt-16 text-center text-sm text-gray-500 dark:text-gray-400 space-y-1">
          <p>Supports multiple languages with automatic translation</p>
          <p>💡 Tip: Paste full song lyrics for more detailed and accurate analysis</p>
        </footer>
      </div>
    </main>
  );
}
